### ISSUE TITLE
Does the library support creating watson conversation services? 

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix/bluemix-go#47]
I checked the example folder and saw examples creating container cluster. However, I could not find any document about creating other blue mix services, e.g., watson conversation. Will this go sdk support such operation? Thanks.

**Comment by ashishth09** [comment]
@huikang ,
Yes. bluemix service example can be found [here](https://github.com/IBM-Bluemix/bluemix-go/tree/master/examples/mccp/service)
Thanks

**Comment by huikang** [comment]
@ashishth09 Thanks for your reply. Now I understand I can provision a watson conversation instance by using this bluemix-go client. I have some further question regarding how to retrieve the service key after provision. For example, this is what I usually do with command line

```bash
cf create-service-key conversation-app convKey
cf service-key conversation-app convKey
```
The output will include the ``url``, ``password``, and ``username`` of the conversation service and I can embed these into my other app.
The bluemix-go client seems no provide such username and password value in it service key. Am I missing anything? Thanks.

**Comment by huikang** [comment]
are the username and password embedded in this credential [1] as a map?

[1] https://github.com/IBM-Bluemix/bluemix-go/blob/defd07a416a323cbcb64aeb477c84875a43061aa/api/mccp/mccpv2/service_keys.go#L28

**Comment by ashishth09** [comment]
yes you got it 😃
