### ISSUE TITLE
The packages under the api directory are not displayed in godoc

### ISSUE THREAD

**Issue by huikang** [IBM-Bluemix/bluemix-go#48]
There are many important packages, like mccp, account. Refresh the godoc does not help solve the issue.

[1] https://godoc.org/github.com/IBM-Bluemix/bluemix-go

**Comment by ashishth09** [comment]
You are right. I will check this. Meanwhile you could run a local copy `godoc -http=:8080`

**Comment by ashishth09** [comment]
Fixed via - https://github.com/golang/gddo/issues/494. Workaround is provided so that we can always update that.

If you find any other piece missing please follow that and it should show right away
Thanks
